import asyncio
import json
import logging
import shlex
from typing import Optional

logger = logging.getLogger(__name__)


async def _run_gws(args: list[str]) -> dict:
    """Run a gws CLI command and return parsed JSON output."""
    cmd = ["gws"] + args
    logger.debug(f"Running: {' '.join(shlex.quote(a) for a in cmd)}")

    proc = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()

    if proc.returncode != 0:
        raise RuntimeError(f"gws command failed (exit {proc.returncode}): {stderr.decode().strip()}")

    return json.loads(stdout.decode())


async def create_meeting_doc(
    title: str,
    created_at: str,
    participants: list[str],
    project_id: Optional[str],
    summary: str,
    topics: list[str],
    action_items: list[dict],
    decisions: list[str],
    issues: list[str],
    folder_id: Optional[str] = None,
) -> str:
    """Create a Google Doc with meeting summary. Returns the doc URL."""

    # 1. Create empty document
    doc_title = f"Meeting Notes: {title}"
    result = await _run_gws([
        "docs", "documents.create",
        "--body", json.dumps({"title": doc_title}),
    ])
    doc_id = result["documentId"]
    logger.info(f"Created Google Doc {doc_id}")

    # 2. Insert content via batchUpdate
    content = _build_doc_content(
        title=title,
        created_at=created_at,
        participants=participants,
        project_id=project_id,
        summary=summary,
        topics=topics,
        action_items=action_items,
        decisions=decisions,
        issues=issues,
    )
    requests = [{"insertText": {"location": {"index": 1}, "text": content}}]
    await _run_gws([
        "docs", "documents.batchUpdate",
        "--documentId", doc_id,
        "--body", json.dumps({"requests": requests}),
    ])

    # 3. Move to folder if specified
    if folder_id:
        try:
            await _run_gws([
                "drive", "files.update",
                "--fileId", doc_id,
                "--addParents", folder_id,
                "--removeParents", "root",
            ])
        except Exception as e:
            logger.warning(f"Could not move doc to folder {folder_id}: {e}")

    return f"https://docs.google.com/document/d/{doc_id}/edit"


def _build_doc_content(
    title: str,
    created_at: str,
    participants: list[str],
    project_id: Optional[str],
    summary: str,
    topics: list[str],
    action_items: list[dict],
    decisions: list[str],
    issues: list[str],
) -> str:
    lines = []

    # Header
    lines.append(f"Meeting Notes: {title}\n")
    lines.append(f"Date: {created_at[:10]}\n")
    if participants:
        lines.append(f"Participants: {', '.join(participants)}\n")
    if project_id:
        lines.append(f"Project: {project_id}\n")
    lines.append("\n")

    # Summary
    lines.append("Summary\n\n")
    lines.append(f"{summary}\n\n")

    # Topics
    if topics:
        lines.append("Topics\n\n")
        for t in topics:
            lines.append(f"• {t}\n")
        lines.append("\n")

    # Action Items
    if action_items:
        lines.append("Action Items\n\n")
        for item in action_items:
            owner = item.get("owner") or "Unassigned"
            task = item.get("task", "")
            due = item.get("due_date") or "-"
            lines.append(f"• [{owner}] {task}  (due: {due})\n")
        lines.append("\n")

    # Decisions
    if decisions:
        lines.append("Decisions\n\n")
        for d in decisions:
            lines.append(f"• {d}\n")
        lines.append("\n")

    # Issues
    if issues:
        lines.append("Issues\n\n")
        for i in issues:
            lines.append(f"• {i}\n")
        lines.append("\n")

    lines.append("---\nGenerated by Meeting Memory Agent\n")

    return "".join(lines)
